spring:
  security:
    jwt:
      key: LibraryManagement
      expire: 7
    filter:
      order: -100
  data:
    redis:
      database: 0
      host: localhost
      port: 6379
  datasource:
    url: jdbc:mysql://localhost:3306/LibraryManagement
    username: root
    password: wbq123456
    driver-class-name: com.mysql.cj.jdbc.Driver